#!/bin/bash

# Inventory
alias ec2='/usr/local/bin/ec2.py'

# 'ansible-playbook'
alias anspb='AWS_PROFILE=prod ansible-playbook -i /usr/local/bin/ec2.py --key-file=~/.ssh/its.private.pem -u root'

# 'ansible'
alias ansp='AWS_PROFILE=prod ansible -i /usr/local/bin/ec2.py --key-file=~/.ssh/its.private.pem -u root'
