#!/bin/bash

source <(kubectl completion zsh)

alias k='kubectl'
alias kx='kubectl config use-context'
alias kpo='kubectl get pod -A -owide'
alias kgs='kubectl get service'
alias kgn='kubectl get namespace'
alias ki='kubectl get ingress -A'

# complete -F __start_kubectl kc
# complete -F _kubectl_config_use-context kx
