" remap leader
let mapleader = " "

" vtr
let g:VtrStripLeadingWhitespace = 0
let g:VtrClearEmptyLines = 0
let g:VtrAppendNewline = 1

" plugins
filetype off                  " required
set nocompatible              " be iMproved, required
set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=/usr/local/opt/fzf
source ~/.vim/plugins.vim

" startup
autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p

" syntax and settings
colorscheme monokai
syntax on
set autoindent
set number
set tabstop=3
set shiftwidth=3
set ruler
set hlsearch

" set autoindent
set expandtab

" NERDTree
map <C-n> :NERDTreeToggle<CR>

" Search and open file
map <C-p> :call fzf#run({'source': 'git ls-files', 'sink': 'e', 'down': '25%'})<CR>
map <C-o> :call fzf#run({'source': 'git ls-files', 'sink': 'tabedit', 'down': '25%'})<CR>

" tab navigation
map <C-q> :tabprevious<CR>
map <C-e> :tabnext<CR>

" automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

" zoom a vim pane, <C-w>= to re-balance
nnoremap <leader>- :wincmd _<cr>:wincmd \|<cr>
nnoremap <leader>= :wincmd =<cr>

" Vim Tmux Runner
nnoremap <leader><CR> :VtrSendFile<cr>
:let g:vtr_filetype_runner_overrides = {'go': 'go run {file}'}

" intuitive splits
set splitbelow
set splitright
