# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export VISUAL=vim
export EDITOR="$VISUAL"
export PATH=$PATH:${HOME}/workspace/.env/bin
export PATH="/usr/local/sbin:$PATH:/Users/hugo.lafleur/bin:/Users/hugo.lafleur/.env/bin"
export GPG_TTY=`tty`

source /opt/homebrew/Cellar/fzf/current/shell/key-bindings.zsh

setopt clobber

[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

if [ -f ~/.git_aliases  ]; then
  . ~/.git_aliases
fi

if [ -f ~/.xp_aliases  ]; then
  . ~/.xp_aliases
fi

if [ -f ~/.ansible_aliases  ]; then
  . ~/.ansible_aliases
fi

# if [ -f ~/.k8s_aliases  ]; then
#   . ~/.k8s_aliases
# fi

if [ -f ~/.azure_aliases  ]; then
   . ~/.azure_aliases
fi

if [ -f ~/.sh_aliases  ]; then
   . ~/.sh_aliases
fi

if [ -f ~/.foundation_aliases  ]; then
   . ~/.foundation_aliases
fi

# fzf completion
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# tmux
_not_inside_tmux() { [[ -z "$TMUX" ]] }
ensure_tmux_is_running() {
  if _not_inside_tmux; then
    tmux a || tat
  fi
}
ensure_tmux_is_running

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
